minor tweaks
AraBlocks/guides pull request #1
Opened 2019-03-27 14:36 UTC by vipyne

2019-03-27 14:45 UTC, jwerle requested changes
The `#` was intentional

2019-03-27 16:17 UTC, vipyne commented
for what?

2019-03-27 17:13 UTC, jwerle commented
aesthetic I guess 🙃

2019-03-27 18:54 UTC, vipyne commented
there's no accounting for taste 🙃

2019-03-28 13:34 UTC, jwerle approved these changes

2019-03-28 13:35 UTC, merged